outdir: 'output'
rscript: '/opt/R/4.2/bin/Rscript'

tasks:
    gdsc_vs_ccle:
        url: 'https://bimsbstatic.mdc-berlin.de/akalin/buyar/flexynesis-benchmark-datasets/dataset1.tgz'
        y: 'Erlotinib,Nilotinib' #,Lapatinib,Crizotinib,Sorafenib,Irinotecan,Topotecan,PD-0325901,Palbociclib,Paclitaxel,Selumetinib,PLX4720'
        data_types: 'gex,cnv'
        type: 'regression'
    tcga_msi:
        url: 'https://bimsbstatic.mdc-berlin.de/akalin/buyar/flexynesis-benchmark-datasets/dataset2.tgz'
        y: 'y'
        data_types: 'gex,meth'
        type: 'classification'
    tcga_tumor_purity:
        url: 'https://bimsbstatic.mdc-berlin.de/akalin/buyar/flexynesis-benchmark-datasets/tcga_tumor_purity.tgz' 
        y: 'IHC'
        data_types: 'gex,cnv'
        type: 'regression'
    msk_met_2021_all:
        url: 'https://bimsbstatic.mdc-berlin.de/akalin/buyar/flexynesis-benchmark-datasets/msk_met_2021_all.tgz'
        y: 'SAMPLE_TYPE' #,SUBTYPE' #PRIMARY_SITE,SUBTYPE,ORGAN_SYSTEM'
        data_types: 'cna,mut'
        type: 'classification'
    msk_met_2021_primary: 
        url: 'https://bimsbstatic.mdc-berlin.de/akalin/buyar/flexynesis-benchmark-datasets/msk_met_2021_primary.tgz'
        y: 'MET_COUNT,MET_SITE_COUNT,FGA,TMB_NONSYNONYMOUS'
        data_types: 'cna,mut'
        type: 'regression'

tools:
    classification: 
        - DirectPred
        - supervised_vae
        - MultiTripletNetwork
    regression:
        - DirectPred
        - supervised_vae

min_features: 250 
features_top_percentile: 0.2 

fusions: 
    - early
    - intermediate

hpo_iterations: 3 
