outdir: 'output_test'

# Base command to run flexynesis 
flexynesis: "flexynesis --use_gpu"

tasks:
    lgg_gbm:
        url: 'https://bimsbstatic.mdc-berlin.de/akalin/buyar/flexynesis-benchmark-datasets/lgggbm_tcga_pub_processed.tgz'
        vars: 
            - 'event:OS_STATUS time:OS_MONTHS'
        data_types: 
            - 'cna'
        tools: 'DirectPred'
        fusions: 
            - intermediate
        min_features: 50 
        features_top_percentile: 3 
        finetuningSampleN: '0' 
        hpo_iterations: 1
        early_stop_patience: 3 
        log_transform: 'False'

