outdir: 'output'
rscript: 'Rscript'

tasks:
    lgg_gbm:
        url: 'https://bimsbstatic.mdc-berlin.de/akalin/buyar/flexynesis-benchmark-datasets/lgggbm_tcga_pub_processed.tgz'
        vars: 
            - 'event:OS_STATUS time:OS_MONTHS'
        data_types: 
            - 'mut,cna'
        tools: 'DirectPred,supervised_vae,DirectPredGCNN:GC,DirectPredGCNN:GAT'
        fusions: 
            - intermediate
        min_features: 1000 
        features_top_percentile: 10
        hpo_iterations: 100
        early_stop_patience: 10 
        log_transform: 'False'

    gdsc_vs_ccle:
        url: 'https://bimsbstatic.mdc-berlin.de/akalin/buyar/flexynesis-benchmark-datasets/dataset1.tgz'
        vars: 
            - 'target:Erlotinib'
            - 'target:Nilotinib'
            - 'target:Crizotinib'
            - 'target:Selumetinib'
            - 'target:PLX4720'
        data_types: 
            - 'gex,cnv'
        tools: 'DirectPred,supervised_vae,DirectPredGCNN:GC,DirectPredGCNN:GAT'
        fusions: 
            - intermediate
        min_features: 1000 
        features_top_percentile: 10
        hpo_iterations: 100
        early_stop_patience: 10 
        log_transform: 'False'
                
    tcga_msi:
        url: 'https://bimsbstatic.mdc-berlin.de/akalin/buyar/flexynesis-benchmark-datasets/dataset2.tgz'
        vars: 
            - 'target:y'
        data_types: 
            - 'gex,meth'
        tools: 'DirectPred,supervised_vae,MultiTripletNetwork,DirectPredGCNN:GC,DirectPredGCNN:GAT'
        fusions: 
            - intermediate
        min_features: 1000 
        features_top_percentile: 10
        hpo_iterations: 100
        early_stop_patience: 10 
        log_transform: 'False'

    metabric:
        url: 'https://bimsbstatic.mdc-berlin.de/akalin/buyar/flexynesis-benchmark-datasets/brca_metabric_processed.tgz'
        vars: 
            - 'target:CLAUDIN_SUBTYPE'
            - 'target:CHEMOTHERAPY'
        data_types:
            - 'gex,cna,mut'
        tools: 'DirectPred,supervised_vae,MultiTripletNetwork,DirectPredGCNN:GC,DirectPredGCNN:GAT'
        fusions: 
            - intermediate
        min_features: 1000 
        features_top_percentile: 10
        hpo_iterations: 100
        early_stop_patience: 10 
        log_transform: 'False'

    singlecell_bonemarrow:
        url: 'https://bimsbstatic.mdc-berlin.de/akalin/buyar/flexynesis-benchmark-datasets/singlecell_bonemarrow.tgz'
        vars:
            - 'target:celltype_l2'
        data_types:
            - 'RNA,ADT' 
        tools: 'DirectPred,supervised_vae,MultiTripletNetwork,DirectPredGCNN:GC,DirectPredGCNN:GAT'
        fusions: 
            - intermediate
        min_features: 1000 
        features_top_percentile: 10
        hpo_iterations: 100
        early_stop_patience: 10 
        log_transform: 'False'

