outdir: 'output'
rscript: '/opt/R/4.2/bin/Rscript'

min_features: 1000 
features_top_percentile: 0.25 

fusions: 
    - early
    - intermediate

hpo_iterations: 5

tasks:
    gdsc_vs_ccle:
        url: 'https://bimsbstatic.mdc-berlin.de/akalin/buyar/flexynesis-benchmark-datasets/dataset1.tgz'
        vars: 
            - 'target:Erlotinib batch:None'
            - 'target:Nilotinib batch:None'
            - 'target:Lapatinib batch:None'
            - 'target:Crizotinib batch:None'
            - 'target:Sorafenib batch:None'
            - 'target:Irinotecan batch:None'
            - 'target:Topotecan batch:None'
            - 'target:PD-0325901 batch:None'
            - 'target:Palbociclib batch:None'
            - 'target:Paclitaxel batch:None'
            - 'target:Selumetinib batch:None'
            - 'target:PLX4720 batch:None'
        data_types: 
            - 'gex,cnv'
            - 'gex'
            - 'cnv'
        tools: 'DirectPred,supervised_vae'
        log_transform: False
    tcga_msi:
        url: 'https://bimsbstatic.mdc-berlin.de/akalin/buyar/flexynesis-benchmark-datasets/dataset2.tgz'
        vars: 
            - 'target:y batch:None'
        data_types: 
            - 'gex,meth'
            - 'meth'
            - 'gex'
        tools: 'DirectPred,supervised_vae,MultiTripletNetwork'
        log_transform: False
    tcga_tumor_purity:
        url: 'https://bimsbstatic.mdc-berlin.de/akalin/buyar/flexynesis-benchmark-datasets/tcga_tumor_purity.tgz' 
        vars: 
            - 'target:IHC batch:None'
        data_types: 
            - 'gex,cnv'
            - 'gex'
            - 'cnv'
        tools: 'DirectPred,supervised_vae'
        log_transform: False
    msk_met_2021_all:
        url: 'https://bimsbstatic.mdc-berlin.de/akalin/buyar/flexynesis-benchmark-datasets/msk_met_2021_all.tgz'
        vars: 
            - 'target:SAMPLE_TYPE batch:None'
            - 'target:ORGAN_SYSTEM batch:None'
        data_types: 
            - 'cna,mut'
        tools: 'DirectPred,supervised_vae,MultiTripletNetwork'
        log_transform: False
    msk_met_2021_primary: 
        url: 'https://bimsbstatic.mdc-berlin.de/akalin/buyar/flexynesis-benchmark-datasets/msk_met_2021_primary.tgz'
        vars: 
            - 'target:MET_SITE_COUNT batch:None'
            - 'target:FGA batch:None'
            - 'target:TMB_NONSYNONYMOUS batch:None'
        data_types: 
            - 'cna,mut'
        tools: 'DirectPred,supervised_vae'
        log_transform: False
    neuroblastoma:
        url: 'https://bimsbstatic.mdc-berlin.de/akalin/buyar/flexynesis-benchmark-datasets/neuroblastoma.tgz'
        vars: 
            - 'target:mycn,subtype batch:dataset'
        data_types:
            - 'gex'
        tools: 'DirectPred,supervised_vae,MultiTripletNetwork'
        log_transform: False
    metabric:
        url: 'https://bimsbstatic.mdc-berlin.de/akalin/buyar/flexynesis-benchmark-datasets/brca_metabric_processed.tgz'
        vars: 
            - 'target:RFS_STATUS,CELLULARITY,HORMONE_THERAPY,CHEMOTHERAPY,LATERALITY,CLAUDIN_SUBTYPE batch:COHORT'
        data_types:
            - 'gex,cna,mut'
            - 'gex,cna'
            - 'cna,mut'
        tools: 'DirectPred,supervised_vae,MultiTripletNetwork'
        log_transform: False

