outdir: 'output'
rscript: 'Rscript'

flexynesis: "flexynesis --hpo_patience 10 --variance_threshold 50"

tasks:
    lgg_gbm:
        url: 'https://bimsbstatic.mdc-berlin.de/akalin/buyar/flexynesis-benchmark-datasets/lgggbm_tcga_pub_processed.tgz'
        vars: 
            - 'event:OS_STATUS time:OS_MONTHS'
        data_types: 
            - 'mut,cna'
        tools: 'DirectPred,supervised_vae,DirectPredGCNN:GC,DirectPredGCNN:GAT'
        fusions: 
            - intermediate
        min_features: 1000 
        features_top_percentile: 25
        hpo_iterations: 100
        finetuningSampleN: '0' 
        early_stop_patience: 10 
        log_transform: 'False'

    ccle_vs_gdsc:
        url: 'https://bimsbstatic.mdc-berlin.de/akalin/buyar/flexynesis-benchmark-datasets/ccle_vs_gdsc.tgz'
        vars:
          #drugs with known targets in civic db and also found in both ccle and gdsc
          - 'target:Crizotinib'
          - 'target:Erlotinib'
          - 'target:Irinotecan'
          - 'target:Lapatinib'
          - 'target:Paclitaxel'
          - 'target:Palbociclib'
          - 'target:Selumetinib'
          - 'target:Sorafenib'
        data_types:
          - 'rna,cnv,mutation'
          - 'rna,mutation'
          - 'mutation'        
        tools: 'DirectPred,supervised_vae'
        fusions: 
            - intermediate
        min_features: 1000 
        features_top_percentile: 25
        finetuningSampleN: '0,100,200,300' 
        hpo_iterations: 100
        early_stop_patience: 10 
        log_transform: 'False'
                
    metabric:
        url: 'https://bimsbstatic.mdc-berlin.de/akalin/buyar/flexynesis-benchmark-datasets/brca_metabric_processed.tgz'
        vars: 
            - 'target:CLAUDIN_SUBTYPE'
            - 'target:CHEMOTHERAPY'
        data_types:
            - 'gex,cna,mut'
        tools: 'DirectPred,supervised_vae,MultiTripletNetwork,DirectPredGCNN:GC,DirectPredGCNN:GAT'
        fusions: 
            - intermediate
        min_features: 1000 
        features_top_percentile: 25
        hpo_iterations: 100
        finetuningSampleN: '0'
        early_stop_patience: 10 
        log_transform: 'False'

    singlecell_bonemarrow:
        url: 'https://bimsbstatic.mdc-berlin.de/akalin/buyar/flexynesis-benchmark-datasets/singlecell_bonemarrow.tgz'
        vars:
            - 'target:celltype_l1'
            - 'target:celltype_l2'
        data_types:
            - 'RNA,ADT' 
        tools: 'DirectPred,supervised_vae,MultiTripletNetwork,DirectPredGCNN:GC,DirectPredGCNN:GAT'
        fusions: 
            - intermediate
        min_features: 1000 
        features_top_percentile: 25
        hpo_iterations: 100
        finetuningSampleN: '0'
        early_stop_patience: 10 
        log_transform: 'False'

